DROP TABLE IF EXISTS "battles";

CREATE TABLE "battles" (
    "id" BIGINT PRIMARY KEY AUTO_INCREMENT,
    "name" VARCHAR(255),
    "battleyear" INTEGER
);

INSERT INTO "battles" ("name", "battleyear") VALUES
('Battle of Five Armies', 2941),
('Battle of Osgiliath', 3018),
('Battle of the Fords of Isen (First)', 3019),
('Battle of the Fords of Isen (Second)', 3019),
('Battle of Helm''s Deep (Battle of the Hornburg)', 3019),
('Battle of the Pelennor Fields', 3019),
('Battle of Dale', 3019),
('Battle of Bywater', 3019),
('Battle of the Morannon', 3019),
('Battle of the Gwathló', 1701),
('Battle of the Last Alliance', 3434),
('Siege of Barad-dûr', 3430),
('First Battle of Beleriand', 1497),
('Dagor-nuin-Giliath (Battle-under-Stars)', 1497),
('Dagor Aglareb (Glorious Battle)', 260),
('Dagor Bragollach (Battle of Sudden Flame)', 455),
('Nirnaeth Arnoediad (Battle of Unnumbered Tears)', 472),
('Fall of Gondolin', 510),
('Sack of Nargothrond', 495),
('Sack of Doriath', 506),
('War of Wrath', 587),
('Battle of Aglon Pass', 455),
('Battle of Sarn Athrad', 489),
('Battle of the Lammoth', 1),
('Battle of Eithel Sirion', 456),
('Battle of Amon Ereb', 506),
('Siege of Angband', 455),
('Siege of Minas Tirith', 3019),
('Skirmish at Weathertop', 3018),
('Attack on Isengard', 3019),
('Destruction of Lake-town (by Smaug)', 2941),
('Skirmish in Ithilien', 3019),
('Battle of the Field of Celebrant', 2510),
('Battle of Fornost', 1975),
('Battle of the Camp', 1944),
('Battle of the Plains', 1856),
('Battle of the Crossings of Erui', 1447),
('Battle of Greenfields', 2747),
('Battle of Azanulbizar (Nanduhirion)', 2799),
('Fall of Minas Ithil', 2002),
('Fall of Númenor', 3319);
